### ISSUE TITLE
inferencing script

### ISSUE THREAD

**Issue by Kristi1217** [lisiqi19971013/EventStream-SR#10]
hI,

I am having a hard time implementing the live-inferencing script, I am using prophesee camera. Can somebody please help me with this. The latency is huge and converting from microsecond to milliseconds increases the latency even more. Any suggestions or help is appreciated.

Thank you.

Regards,
K!

**Comment by lisiqi19971013** [comment]
Hi, Kristi

According to my experience, it may be very difficult to achieve real-time super-resolution inference for prophesee cameras, whose own spatial resolution is too high, resulting in too huge amount of data.  We were using a DVS128 camera with the spatial resolution of 128×128, which is already difficult. So I think it may be tough to implement for the prophesee camera. I haven't used the prophesee camera yet, it might work if it had some function to limit its own event rate.

Siqi
