### ISSUE TITLE
在图像重建应用上的问题

### ISSUE THREAD

**Issue by Antleaf-0921** [lisiqi19971013/EventStream-SR#11]
感谢你们的工作！在阅读贵团队论文时，我注意到你们在论文的4.5节中提到了用生成的HR event streams来进行图像重建，其中你们运用了E2VID来作为你们的重建方法。我想问一下你们是否也将得到的HR版本的N-MNIST、CIFAR10-DVS、ASL-DVS也用于图像重建？你们在使用E2VID进行重建时，使用的是预训练模型还是自己从头训练？因为我注意到E2VID方法似乎并没有给出训练的代码，期待着你们的回复。

**Comment by lisiqi19971013** [comment]
1. 在使用E2VID进行重建时，使用的事官方预训练模型，而没有重新训练。需要注意的是，官方的预训练模型就是在Event Camera Dataset上进行训练的。因此，如我们文中所述，可以认为在Event Camera Dataset上超分辨率的效果越好（生成的HR事件流与真值越像），则其使用官方预训练模型重建的效果越好。
2. 我们没有在N-MNIST、CIFAR10-DVS、ASL-DVS数据集上进行重建，如1所述，官方的模型是在Event Camera Dataset上训练的，使用其他数据集进行重建，无法证明超分辨率与图像重建效果之间的关系，即，重建图像效果好的事件流，可能是更符合Event Camera Dataset中的事件流的分布，而不是其他数据集本身的真值高分辨率事件流的分布。
