### ISSUE TITLE
about the spike of output

### ISSUE THREAD

**Issue by kkkkkkip** [lisiqi19971013/EventStream-SR#2]
你好我有一个关于trainNmnist.py的output输出的问题，对应脉冲神经元输出，按照我的理解应该是二值的脉冲序列，为一串的0或者1，但是我print出来的output不为0 or 1，而是具体的值。这点有点不明白，希望能得到您的答复

**Comment by lisiqi19971013** [comment]
如果方便的话，请描述一下output不为0或1的话，具体的值是指什么？是类似0.52  1.78这种小数值，还是存在2 3 4这样的整数值？
如果是前者，请检查下model的最后输出是否有self.slayer3.spike(·)函数，这个我记得是用于从神经元膜电位计算对应output spike的。

**Comment by kkkkkkip** [comment]
你好，output的输出为小数值和0，且部分小数值为负数（有正有负），model.py有self.slayer3.spike(·)函数，该函数return的结果就应该是output，对应代码spikes_layer_3 = self.slayer3.spike(self.upconv1(self.slayer3.psp(spikes_layer_2)) + psp1_1)。我理解的spike函数应该是输出脉冲的（0 or 1）,从神经元膜电位计算对应output spike的。但是不清楚为什么输出是具体值（小数），请问您跑出的output全部为0 or 1值吗，我这边没有修改代码，但是跑出来的结果是数字。

**Comment by lisiqi19971013** [comment]
这看起来很奇怪，我刚刚又在我本地尝试了一下，输出的output确实是只有0或者1的二值。要不你检查一下版本？是不是这个slayerPytorch的库更新了？你试下在model.py文件下面运行一下下面的代码，看下输出？
```
    import os
    from slayerSNN.spikeFileIO import event

    def readNpSpikes(filename, timeUnit=1e-3):
        npEvent = np.load(filename)
        return event(npEvent[:, 1], npEvent[:, 2], npEvent[:, 3], npEvent[:, 0] * timeUnit * 1e3)

    x = readNpSpikes('../dataset/N-MNIST/SR_Test/LR/4/10.npy')
    x = x.toSpikeTensor(torch.zeros((2, 17, 17, 350)))
    x = torch.unsqueeze(x, dim=0).cuda()

    netParams = snn.params('./nMnist/network.yaml')
    m = NetworkBasic(netParams)
    m = torch.nn.DataParallel(m).cuda()
    with torch.no_grad():
        out = m(x)
    print((out == 0).sum(), (out == 1).sum(), ((out != 0) & (out != 1)).sum())
```
我这个是随便找了一个样本测试了一下，在我这里跑出来是这样的：
![image](https://user-images.githubusercontent.com/22660386/228433864-f97d8727-e3a9-4da0-88df-20f524b1d922.png)
由于我的这个膜电位设置的特别高，在模型没训练之前输出基本上都是0，但也确实没有除了0和1之外的数值，你那边测试一下看一下？

**Comment by kkkkkkip** [comment]
你好我跑了一下上述的代码，((out != 0) & (out != 1)).sum())还是不为零，我去确认一下是不是slayerPytorch的库更新了，麻烦了
