### ISSUE TITLE
about cifar10

### ISSUE THREAD

**Issue by kkkkkkip** [lisiqi19971013/EventStream-SR#3]
Hello, I cannot download the data set of cifar10 you provided successfully, but I can download the n-mnist data set you provided. I would like to ask if there are other methods or ways to provide the cifar10 you have processed

**Comment by lisiqi19971013** [comment]
Hello, try this Baidu Netdisk link: https://pan.baidu.com/s/1VtKZ_MHf_E3-BTtKzaKoUQ (extract code: g5fz).

**Comment by kkkkkkip** [comment]
Thank you for your help. I have finished downloading the data set

**Comment by kkkkkkip** [comment]
Hello, I am unable to download the ASL dataset. Can you provide a download link for Baidu Netdisk？
