### ISSUE TITLE
Data preprocessing pipeline to prepare lr from hr

### ISSUE THREAD

**Issue by tangores** [lisiqi19971013/EventStream-SR#5]
Thank you for sharing your work. Do you plan on uploading the data preprocessing pipeline?

**Comment by lisiqi19971013** [comment]
Actually, we obtain LR event stream from original HR event stream. As mentioned in the paper, we obtain LR event stream by merging the events in each $2\times2$ kernel with a stride of 2. In practice, it is achieved by the code just like:

```
    LR = np.zeros(HR.shape).astype(np.int32)
    LR[:, 0] = HR[:, 0]                           # t
    LR[:, 3] = HR[:, 3]                           # p
    LR[:, 2] = (HR[:, 2] / 2).astype(np.int32)    # x
    LR[:, 1] = (HR[:, 1] / 2).astype(np.int32)    # y
    LR = np.unique(LR, axis=0)
```


Meanwhile, to match the simulation precision, we adjust temporal resolution of the event stream to millisecond by the code like:

```
    HR[:, 0] = (HR[:, 0] / 1000).astype(np.int32)   # from us to ms
    HR = np.unique(HR, axis=0)
```

**Comment by waseemshariff126** [comment]
This worked for me but the loss of events are very large.
