### ISSUE TITLE
About the ASL-DVS dataset download

### ISSUE THREAD

**Issue by kkkkkkip** [lisiqi19971013/EventStream-SR#6]
I'm sorry to bother you, but the download address you provided could not be successfully downloaded. I am in urgent need of this data set at present,. Can you provide me with other download methods when you are free

**Comment by lisiqi19971013** [comment]
It could be downloaded from: https://pan.baidu.com/s/1OlmoD9ZragSJTHx8Ffb2pA , extract code: 3eby

**Comment by kkkkkkip** [comment]
Many thanks
