### ISSUE TITLE
Inferencing sampling TimeBin handling

### ISSUE THREAD

**Issue by Kristi1217** [lisiqi19971013/EventStream-SR#8]
Hello Siqi,

I was really impressed by your work on Event Stream Super Resolution. I have a couple of questions for you. 
1) Firstly, do you have any plans to share the inferencing script? 
2) Secondly, I'm curious about how the network handles timebins in real-time SR inferencing.

Thank you!

**Comment by Kristi1217** [comment]
Any suggestions? please email kritofferlame@gmail.com

**Comment by lisiqi19971013** [comment]
Hello, 
1. The inference script is contained in each dataset folder, e.g., /nMnist/testNmnist.py.
2. For real-time SR inferencing, we convert events within each received packet (30ms, according to dvs128 camera) into 30 time bins with millisecond precision and forward it into our model.

**Comment by Kristi1217** [comment]
Thank you for your prompt response. I apologize for any confusion. My initial inquiry pertained to real-time inference. Could you kindly inform me if there are plans to provide the real-time inferencing script? Much appreciated.

**Comment by lisiqi19971013** [comment]
Oh, the code for real-time inference was stored on the Xavier we were using at the time. Time has passed too long for us to find that Xavier, so we are unable to find that script now. I'm sorry for that.

**Comment by Kristi1217** [comment]
hI, 

I am having a hard time implementing the live-inferencing script, can somebody please help me with this. The latency is huge and converting from microsecond to milliseconds increases the latency even more. Any suggestions or help is appreciated. 

Thank you. 

Regards,
K!

**Comment by Kristi1217** [comment]
> Oh, the code for real-time inference was stored on the Xavier we were using at the time. Time has passed too long for us to find that Xavier, so we are unable to find that script now. I'm sorry for that.

hI,

I am having a hard time implementing the live-inferencing script, can somebody please help me with this. The latency is huge and converting from microsecond to milliseconds increases the latency even more. Any suggestions or help is appreciated.

Thank you.

Regards,
K!
